-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."gas_pumps" add column "is_smart" boolean
--  not null default 'false';
